-- Criação de todas as tabelas da aplicação

CREATE TABLE TB_MTT_ESTADO ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    sigla_estado VARCHAR2(2) NOT NULL, 
    nome_estado VARCHAR2(25) NOT NULL 
);

CREATE TABLE TB_MTT_CIDADE ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    TB_MTT_ESTADO_id NUMBER NOT NULL, 
    nome_cidade VARCHAR2(65) NOT NULL, 
    numero_ddd NUMBER(2) NOT NULL 
);

CREATE TABLE TB_MTT_FILIAL ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE TB_MTT_USUARIO ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    username VARCHAR2(50) NOT NULL UNIQUE, 
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) NOT NULL
);

CREATE TABLE TB_MTT_VEICULO ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    TB_MTT_USUARIO_id NUMBER NOT NULL, 
    placa_antiga VARCHAR2(7) NULL, 
    placa_nova VARCHAR2(10) NOT NULL UNIQUE, 
    tipo_veiculo VARCHAR2(75) NOT NULL 
);

CREATE TABLE TB_MTT_CAMERA ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    TB_MTT_FILIAL_id NUMBER NOT NULL, 
    modelo VARCHAR2(40) NOT NULL 
);

CREATE TABLE TB_MTT_IOT ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    TB_MTT_VEICULO_id NUMBER NOT NULL, 
    status SMALLINT NOT NULL CHECK (status IN (0, 1)), 
    tipo VARCHAR2(30) NOT NULL 
);

CREATE TABLE TB_MTT_LOGRADOURO ( 
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    TB_MTT_USUARIO_id NUMBER NULL, 
    TB_MTT_FILIAL_id NUMBER NULL, 
    TB_MTT_CIDADE_id NUMBER NOT NULL, 
    nome_logradouro VARCHAR2(100) NOT NULL, 
    numero_logradouro VARCHAR2(10) NOT NULL, 
    cep VARCHAR2(8) NOT NULL,
    complemento VARCHAR2(50) NULL
);

CREATE TABLE TB_MTT_FINANCAS (
    agencia NUMBER(4), 
    conta NUMBER(8), 
    saldo NUMBER(10, 2)
);