ALTER TABLE TB_MTT_CIDADE 
    ADD CONSTRAINT TB_MTT_CIDADE_ESTADO_FK FOREIGN KEY (TB_MTT_ESTADO_id) REFERENCES TB_MTT_ESTADO (id);

ALTER TABLE TB_MTT_VEICULO 
    ADD CONSTRAINT TB_MTT_VEICULO_USUARIO_FK FOREIGN KEY (TB_MTT_USUARIO_id) REFERENCES TB_MTT_USUARIO (id);

ALTER TABLE TB_MTT_CAMERA 
    ADD CONSTRAINT TB_MTT_CAMERA_FILIAL_FK FOREIGN KEY (TB_MTT_FILIAL_id) REFERENCES TB_MTT_FILIAL (id);

ALTER TABLE TB_MTT_IOT 
    ADD CONSTRAINT TB_MTT_IOT_VEICULO_FK FOREIGN KEY (TB_MTT_VEICULO_id) REFERENCES TB_MTT_VEICULO (id);

ALTER TABLE TB_MTT_LOGRADOURO 
    ADD CONSTRAINT TB_MTT_LOGRADOURO_USUARIO_FK FOREIGN KEY (TB_MTT_USUARIO_id) REFERENCES TB_MTT_USUARIO (id);

ALTER TABLE TB_MTT_LOGRADOURO 
    ADD CONSTRAINT TB_MTT_LOGRADOURO_FILIAL_FK FOREIGN KEY (TB_MTT_FILIAL_id) REFERENCES TB_MTT_FILIAL (id);

ALTER TABLE TB_MTT_LOGRADOURO 
    ADD CONSTRAINT TB_MTT_LOGRADOURO_CIDADE_FK FOREIGN KEY (TB_MTT_CIDADE_id) REFERENCES TB_MTT_CIDADE (id);